### ISSUE TITLE
Proxying services on a named docker-compose network

### ISSUE THREAD

**Issue by psychemedia** [jupyterhub/jupyter-server-proxy#102]
If we run a Jupyter notebook server in a docker container and docker-compose with another application (eg OpenRefine) running a separate container, eg with a docker-compose script along the lines of:

```
version: '3.5'

services:
  refine:
    container_name: refine_container
    image: psychemedia/openrefinedemo
    ports:
      - "3333:3333"
    networks:
      - jupyternet
    restart: unless-stopped

  jupyter:
    container_name: refine_jupyter_notebook_container
    #image: jupyter/minimal-notebook
    build: ./
    environment:
      JUPYTER_TOKEN: 'letmein'
    ports:
      - "80:8888"
    networks:
      - jupyternet
    volumes:
      - jupyter_notebook_config.py:/home/jovyan/.jupyter/jupyter_notebook_config.py
    restart: unless-stopped

networks:
  jupyternet:
    driver: bridge
```

build a notebook sever container with the server proxy package installed:

```
FROM jupyter/minimal-notebook

RUN pip install git+https://github.com/jupyterhub/jupyter-server-proxy
```

and mounting a traitlet config file along the lines of:

```
c.ServerProxy.servers = {
    'openrefine': {
        #I don't need a command, server is already running?
        #'command': ['/home/jovyan/.openrefine/openrefine-2.8/refine', '-p', '{port}','-d','/home/jovyan/openrefine'],
        #Can we specify network: http://refine_container
        'port': 3333,
        'timeout': 120,
        'launcher_entry': {
            'title': 'OpenRefine'
        },
    },
}
```

is there a way of:

- specifying the service we want to proxy is on http://refine_container:3333 available (which is available over `jupyternet`);
- avoiding the start command (because the service we want to proxy is already free running in the connected container.

I guess another way to do it would be just to build OpenRefine into the notebook container and then letting the traitlet handle starting OpenRefine; but it would open up more possibilities in general if we could just compose the OpenRefine container in?
